# -*- coding: utf-8 -*-
"""Ejercicos Programacion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TNnjdR0eOz9i7uXaUFpn0Ia2kSkTyAfq
"""

lado = float(input("Ingrese el valor del lado del cuadrado: "))

area = lado ** 2

print("La superficie del cuadrado es:", area)

num1 = 43
num2 = 7


suma = num1 + num2
resta = num1 - num2
multiplicacion = num1 * num2
division = num1 / num2


print("Suma:", suma)
print("Resta:", resta)
print("Multiplicación:", multiplicacion)
print("División:", division)

numero = 36

numero += 5
print(numero)

numero -= 3
print(numero)

numero *= 2
print(numero)

numero /= 4
print(numero)

nombre = "Pepito"
apellido = "Suarez"

nombre_completo = nombre + " " + apellido

print(nombre_completo)

a = True
b = False

res_and = a and b
res_or = a or b
res_not_a = not a
res_not_b = not b

print(res_and)
print(res_or)
print(res_not_a)
print(res_not_b)

n1 = 5.68
n2 = 10.16

redondeo_n1 = round(n1)
redondeo_n2 = round(n2)

potencia = n1 ** n2

print(redondeo_n1)
print(redondeo_n2)
print(potencia)

lista1 = [1, 2, 3, 4, 5, 6]
lista2 = [10, 11, 12, 13, 14, 15]

concatenacion = lista1 + lista2
rep_lista1 = lista1 * 2
rep_lista2 = lista2 * 2

print(concatenacion)
print(rep_lista1)
print(rep_lista2)

num1 = 17
num2 = 21

print(num1 < num2)
print(num1 > num2)
print(num1 == num2)

a = 17
b = 5

div_entera = a // b
modulo = a % b

print(div_entera)
print(modulo)

tupla1 = (7, 13, 2)
tupla2 = (9, 4)

concatenacion = tupla1 + tupla2
repeticion = tupla1 * 2

print(concatenacion)
print(repeticion)

num_entero = 19        # tipo int
num_decimal = 3.2     # tipo float

suma = num_entero + num_decimal
resta = num_entero - num_decimal
multiplicacion = num_entero * num_decimal
division = num_entero / num_decimal

print(suma)
print(resta)
print(multiplicacion)
print(division)